### ISSUE TITLE
"#include "ImGuiFrame.hpp"" not in the correct folder

### ISSUE THREAD

**Issue by LudoDeve** [MariuszJozef/SDLImGuiTriangle#1]
Hi,

the compilation fails because OpenGLContext.hpp and ImGuiFrame.hpp are included in SDLWindow.cpp instead of SDLWindow.hpp       :
unique_ptr.h:79:16: error: invalid application of 'sizeof' to incomplete type 'SDLImGui::OpenGLContext'
unique_ptr.h:79:16: error: invalid application of 'sizeof' to incomplete type 'SDLImGui::ImGuiFrame'

Anyway, when I moved #include "OpenGLContext.hpp"  and #include "ImGuiFrame.hpp"
from SDLWindow.cpp  to SDLWindow.hpp 
the compilation works well.
But I still can not excute the code

the debugger (GNU gdb (GDB) 8.1) stops in "SDLWindow.cpp" at imGuiFrame = std::make_unique<ImGuiFrame>(sdlWindow, openGLContext.get());

So is it the last version of the code that is commited ?

**Comment by MariuszJozef** [comment]
@LudoDeve 

Thank you for bringing this to my attention. I see what's gone wrong: there was a missing directory External/glad4.1 with third-party code in there which configures OpenGL. It seems that it was ignored by my .gitignore when I commited the final version of this demo project. The repo is now updated with a new commit ab7e5572f7d2e29475a8b45d34bcd5a6719d275b.

It should work for you now without any changes of header includes that you mentioned, merely git pull to get the missing glad4.1.

If for some reason glad4.1 doesn't work on your machine, you can download a suitable version from their official page:

https://glad.dav1d.de

and replace it the same location: External/glad4.1.

I'm sorry I overlooked this somehow, I hope you didn't loose much time because of this; I appricate the info.

All the best,
Mariusz

**Comment by LudoDeve** [comment]
thank you
